version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.21.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build
          command: npm install

      - run:
          name: Lint code
          command: npm run lint
