version: 2
jobs:
  build:
    docker:
      - image: circleci/node:20.19.5

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build
          command: npm install

      - run:
          name: Lint code
          command: npm run lint
